---
version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  registries:
    - ghcr
  schedule:
    interval: weekly
  groups:
    docker:
      update-types: [minor, patch, major]

- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
  groups:
    gomod:
      update-types: [minor, patch]

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  groups:
    github-actions:
      update-types: [minor, patch]
