name: kube-service-exporter
sources:
  dep: true
allowed:
- mit
- apache-2.0
- bsd-2-clause
- bsd-3-clause
- mpl-2.0
- isc
reviewed:
  dep:
  - github.com/ghodss/yaml
  - github.com/gogo/protobuf/proto
  - github.com/gogo/protobuf/sortkeys
  - github.com/juju/ratelimit
  - github.com/magiconair/properties
  - github.com/pmezard/go-difflib/difflib
  - github.com/stretchr/testify/assert
  - github.com/stretchr/testify/require
  - github.com/stretchr/testify/suite
  - golang.org/x/crypto/ssh/terminal
  - golang.org/x/net/context
  - golang.org/x/net/http2
  - golang.org/x/sys/unix
  - golang.org/x/sys/windows
  - golang.org/x/text/cases
  - golang.org/x/text/internal
  - golang.org/x/text/internal/gen
  - golang.org/x/text/internal/tag
  - golang.org/x/text/internal/triegen
  - golang.org/x/text/internal/ucd
  - golang.org/x/text/language
  - golang.org/x/text/runes
  - golang.org/x/text/secure/precis
  - golang.org/x/text/unicode/cldr
  - golang.org/x/text/unicode/rangetable
  - golang.org/x/text/width
  - gopkg.in/inf.v0
  - gopkg.in/yaml.v2
