apiVersion: v1
kind: Namespace
metadata:
  name: fake-statsd
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: fake-statsd
  namespace: fake-statsd
  labels:
    app: fake-statsd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-statsd
  template:
    metadata:
      labels:
        app: fake-statsd
    spec:
      containers:
      - name: fake-statsd
        image: zendesk/statsd-logger
        imagePullPolicy: Always
        ports:
        - name: statsd
          containerPort: 8125
          protocol: UDP
---
kind: Service
apiVersion: v1
metadata:
  name: fake-statsd
  namespace: fake-statsd
  labels:
    app: fake-statsd
spec:
  type: NodePort
  selector:
    app: fake-statsd
  ports:
  - name: statsd
    protocol: UDP
    port: 28125
    targetPort: statsd