---
apiVersion: v1
kind: Service
metadata:
  name: consul
spec:
  ports:
  - port: 8500
    protocol: TCP
    targetPort: 8500
  selector:
    run: consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: consul
  name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      run: consul
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: consul
    spec:
      containers:
      - image: consul
        imagePullPolicy: Always
        name: consul
        ports:
        - containerPort: 8500
          protocol: TCP
